### ISSUE TITLE
there is no .deb file

### ISSUE THREAD

**Issue by drossetti** [Mellanox/nv_peer_memory#2]
Ubuntu is one interesting distro for many

**Comment by drossetti** [comment]
we cloned this repo, then after installing the required pkg:
$ sudo apt-get install debhelper

we got:
$ dpkg-buildpackage -us -uc
dpkg-buildpackage: source package nvidia-peer-memory
dpkg-buildpackage: source version 1.0-0
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by Alaa Hleihel <alaa@mellanox.com>
dpkg-buildpackage: host architecture amd64
 dpkg-source --before-build nv_peer_memory-master
 fakeroot debian/rules clean
dh clean --with dkms
   dh_testdir
   dh_clean
 dpkg-source -b nv_peer_memory-master
dpkg-source: error: can't build with source format '3.0 (quilt)': no upstream tarball found at ../nvidia-peer-memory_1.0.orig.tar.{bz2,gz,lzma,xz}
dpkg-buildpackage: error: dpkg-source -b nv_peer_memory-master gave error exit status 255

**Comment by haggaie** [comment]
According to my colleague, in order to build a deb file you need to first prepare a tarball with the source code. Prepare a source code directory with name `nvidia-peer-memory-<major version>`, eg. `nvidia-peer-memory-1.0`. Note: the major version (1.0) in this case is taken from first line in  `debian/changelog`  (`nvidia-peer-memory (1.0-0) unstable; urgency=low`)
Create a tarball: 

    $ tar czf nvidia-peer-memory_1.0.orig.tar.gz nvidia-peer-memory-1.0

Then create the deb package:

    $ cd nvidia-peer-memor-1.0
    $ dpkg-buildpackage -us -uc

**Comment by drossetti** [comment]
not heard any more complains. closing this
