### ISSUE TITLE
Dependency linux-headers | linux-headers-generic is not present on Debian

### ISSUE THREAD

**Issue by byronyi** [Mellanox/nv_peer_memory#23]
Would you consider adding `linux-headers-amd64` as an alternative dependency? It might need a couples of other packages for other arches, but I am not aware of a meta package like `linux-headers-generic` in Debian as in Ubuntu.

**Comment by ferasd** [comment]
+ @alaahl

**Comment by alaahl** [comment]
Actually, I also had some issues with the linux sources dependency in some OFED packages in the past.
Eventually, I moved it to "Recommends:" tag instead of "Depends:", and now it looks like this:

Recommends: linux-headers-arm64 | linux-headers-powerpc | linux-headers-ppc64 | linux-headers-ppc64le | linux-headers-amd64 | linux-headers-generic | linux-headers

**Comment by byronyi** [comment]
Would this change be applied to the project? Certainly I could change this by myself, but it would be better handled else where.

**Comment by alaahl** [comment]
submitted https://github.com/Mellanox/nv_peer_memory/pull/25

**Comment by byronyi** [comment]
Sorry just saw this. Thanks @alaahl!
